modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="shfa"
version="1.0.1"
displayName="SHFA"
displayURL="https://www.ryanbester.com"
authors="Ryan Bester"
description='''
Same Hitboxes For All. Makes the hitboxes of glass panes, iron bars and other blocks the same the size of a full block.
'''
